### ISSUE TITLE
Don't Run Concurrency on `main`

### ISSUE THREAD

**Issue by ric-evans** [WIPACrepo/SkyDriver#12]
Running with concurrency leads to false-fails due to cancels. Note, there's nothing wrong with this, it just looks weird to see an :x: when things go correctly

change to:
```yaml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # don't cancel on main/master/default
  cancel-in-progress: ${{ format('refs/heads/{0}', github.event.repository.default_branch) != github.ref }}
```
